name: Lintcheck

on: workflow_dispatch

jobs:
  codecheckout:
    runs-on: ubuntu-22.04
    steps:
    - name: codecheckout
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.11"

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check .

      # Step 3: Install linting tools
  
